"""add_author_id_to_products

Revision ID: 9a8287f3f1a4
Revises: 0d07d619631a
Create Date: 2026-07-03 15:50:39.812978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a8287f3f1a4'
down_revision: Union[str, Sequence[str], None] = '0d07d619631a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('author_id', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'products', 'users', ['author_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'author_id')
    # ### end Alembic commands ###
